# Generated by Django 3.2.18 on 2023-03-18 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMnagements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.CharField(max_length=8)),
                ('in_time', models.CharField(blank=True, max_length=4, null=True)),
                ('out_time', models.CharField(blank=True, max_length=4, null=True)),
                ('work_minutes', models.CharField(default='0', max_length=4)),
                ('overtime_minutes', models.CharField(default='0', max_length=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employees')),
            ],
            options={
                'db_table': 't_time_managements',
            },
        ),
    ]
